### ISSUE TITLE
Undefined Implemention

### ISSUE THREAD

**Issue by eUTXOpro** [tcfev/TrueWE#1]
Claims to use cryptocurrency to solve problem but no blockchain solution is defined in the scope of the whitepaper.

**Comment by Decentralized-Singularity** [comment]
> Claims to use cryptocurrency to solve problem but no blockchain solution is defined in the scope of the whitepaper.

**Comment by Decentralized-Singularity** [comment]
I guess I didn't get your point well. Are you asking which blockchain will be used?
